### ISSUE TITLE
Refactor *all* tables to new `StreamedTable` versions

### ISSUE THREAD

**Issue by ThePhisch** [rucio/webui#215]
## Description
Going forward, all tanstack (streamed) tables will use the generic `StreamedTable` component and its associated components (such as `TableFilterString`, `TableFilterDiscrete`, etc.). At the same time, most tables still use the old and inconvenient method of designing tables.

## Task
Refactor all of these tables and bring them up to date. This means:
* Using the typed and generic `StreamedTable`
* Type the data shown in the table
* Create associated table components where necessary
* using fixtures to the greatest extent possible
* Work on style, accessibility, responsiveness and dark mode
* `StreamedTable` should be able to handle selections
  * Extra information cards (such as the one in `PageDIDDatasetReplicas`) should not be handled *within* the table (better to inform the parent component that a single element has been selected and let the parent handle the card).

In the end, it should be possible to remove all old table components from the `StreamedTables` folder.

## Progress

- [x] Page DID Contents -> renamed to Page DID By Type
- [x] Page DID Dataset Replicas
- [x] Page DID Filereplicas
- [x] Page DID Filereplicas D
- [x] Page DID Metadata
- [x] Page DID Parents -> merged with Page DID By Type
- [x] Page DID Rules
- [x] DID Select Table
- [x] RSE Quota Table
- [x] DID List Table

**Comment by ThePhisch** [comment]
Completed as per #216
